version: "3.9"
services:
  dog-backend:
    build: .
    container_name: dog-backend
    ports:
      - "8000:8000"
    env_file:
      - .env_example
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: database
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    networks:
      - app-network
    # Исправлено объявление тома:
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Ссылка на том, объявленный в корне

  nginx:
    image: nginx:1.26.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dog-backend
    networks:
      - app-network

# Объявляем тома и сети на верхнем уровне:
networks:
  app-network:

volumes:
  postgres_data:  # Том объявлен здесь
